spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local: oauth,actuator
      docker: oauth,actuator
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: sparkle-note

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.sparklenote: DEBUG
    com.sparklenote.user.jwt: DEBUG  # JWT 관련 로그 상세히 보기

springdoc:
    swagger-ui:
      operations-sorter: get-post-put-delete
      tagsSorter: alpha
