# application-oauth.yml
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            redirect-uri: ${OAUTH2_KAKAO_REDIRECT_URI}
            client-name: Kakao
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id