global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['sparkle-note-backend:8080']
    basic_auth:
      username: admin  # ${ACTUATOR_USER}와 같은 값 사용
      password: admin  # ${ACTUATOR_PASSWORD}와 같은 값 사용